### ISSUE TITLE
issue with encoding

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub-modules-linkpreview#18]
As a french user, there are a lot of links to french websites.

Preview appears like this (minus the space ... otherwise github translate the accent correctly)

> Un hommage au pilote l&eacute ;gendaire Ayrton Senna

instead of 

> Un hommage au pilote légendaire Ayrton Senna

All accent and special chars are incorrect.

I guess it's a UTF-8 encoding issue...

**Comment by luke-** [comment]
Can you please provide some example URLs and Screenshots?

**Comment by Reuns** [comment]
You can try to add this url : https://store.playstation.com/fr-fr/product/EP0001-PPSA01870_00-FC6EDSTANDARD000/
And look at this mess ^^
![image](https://user-images.githubusercontent.com/19529531/138174968-c2a3d63d-a8a5-47c2-b37c-3d2bc22fe1b3.png)

Youtube Videos have the same issue : https://www.youtube.com/watch?v=qc3HBnPanx0
![image](https://user-images.githubusercontent.com/19529531/138175163-8597e006-44bc-4157-9038-240cb7bccec0.png)

Hope it'll help...

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/linkpreview/pull/7:

<img width="660" alt="fr" src="https://user-images.githubusercontent.com/6995524/138269210-40c1fdc5-20be-401c-a832-0cbc1119fdcd.png">

We already fixed similar issue here https://github.com/humhub/linkpreview-issues/issues/16, there https://github.com/humhub/linkpreview/pull/4/files#diff-b1d65a17c66062f6504e240ef9ec053b8ed6dad76fc3b78390246efa7f546aadR89 I added `htmlentities()` and it worked well for these cases, but on current it didn't work, so I changed to `html_entity_decode()` because the current fr case has a `&amp;` in the `<title>FAR CRY®6 - Édition standard PS4 &amp; PS5</title>`.

Previous cz samples work well with new PR too:

<img width="662" alt="cz" src="https://user-images.githubusercontent.com/6995524/138270535-ce4d623c-084a-477a-bb5c-87002ca425d5.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks!

**Comment by luke-** [comment]
@Reuns Version 1.15.6 should fixes the problem

**Comment by Reuns** [comment]
That's perfect !
Thank you.

**Comment by Reuns** [comment]
Hi !
Issue is still here for youtube video
Example with : https://www.youtube.com/watch?v=qc3HBnPanx0
![image](https://user-images.githubusercontent.com/19529531/143623636-064c5200-df88-44d3-8359-f9ee232c714c.png)
